server:
  port: 7810

spring:
  datasource:
    druid:
      url: jdbc:mysql://114.215.196.38:3306/business_member?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: root

rocketmq:
  name-server: 10.3.133.161:9876
  producer:
    group: member-group