server:
  port: 7810

spring:
  datasource:
    druid:
      url: ""
      username: root
      password: root
    # topic

rocketmq:
  name-server: 10.3.133.161:9876
  producer:
    group: member-group